import { getAgentPersonalityProfile } from "./persona-prompts";
import { resolveCommercialAgentKey } from "./commercial-agents";
import type { AgentStablePersonality, PersonalityLevel, ToneStyle, EnergyStyle } from "./conversation-personality-state";

const TRAITS: Record<string, Omit<AgentStablePersonality, "agentId" | "displayName">> = {
  grace: {
    communicationStyle: "Conseillère digitale élégante, pédagogie légère",
    warmthLevel: "high",
    professionalismLevel: "high",
    energyBaseline: "medium",
    patienceLevel: "high",
    commercialStyle: "conseiller",
    empathyLevel: "high",
    formalityLevel: "high",
    salesPressure: "low",
    energyStyle: "calm",
    toneStyle: "elegant",
  },
  vanessa: {
    communicationStyle: "Relation client douce, suivi commande",
    warmthLevel: "high",
    professionalismLevel: "high",
    energyBaseline: "medium",
    patienceLevel: "high",
    commercialStyle: "premium",
    empathyLevel: "high",
    formalityLevel: "medium",
    salesPressure: "low",
    energyStyle: "calm",
    toneStyle: "warm",
  },
  naomi: {
    communicationStyle: "Écoute active, fidélisation",
    warmthLevel: "high",
    professionalismLevel: "medium",
    energyBaseline: "medium",
    patienceLevel: "high",
    commercialStyle: "premium",
    empathyLevel: "high",
    formalityLevel: "medium",
    salesPressure: "low",
    energyStyle: "calm",
    toneStyle: "warm",
  },
  cynthia: {
    communicationStyle: "Premium sobre, net",
    warmthLevel: "medium",
    professionalismLevel: "high",
    energyBaseline: "low",
    patienceLevel: "high",
    commercialStyle: "premium",
    empathyLevel: "medium",
    formalityLevel: "high",
    salesPressure: "low",
    energyStyle: "calm",
    toneStyle: "elegant",
  },
  diane: {
    communicationStyle: "Boutique haut de gamme local",
    warmthLevel: "medium",
    professionalismLevel: "high",
    energyBaseline: "low",
    patienceLevel: "high",
    commercialStyle: "premium",
    empathyLevel: "medium",
    formalityLevel: "high",
    salesPressure: "low",
    energyStyle: "calm",
    toneStyle: "elegant",
  },
  bryan: {
    communicationStyle: "Vendeur terrain startup, concret",
    warmthLevel: "medium",
    professionalismLevel: "medium",
    energyBaseline: "high",
    patienceLevel: "medium",
    commercialStyle: "closer",
    empathyLevel: "medium",
    formalityLevel: "medium",
    salesPressure: "medium",
    energyStyle: "dynamic",
    toneStyle: "direct",
  },
  brice: {
    communicationStyle: "Closer moderne, orienté résultat",
    warmthLevel: "medium",
    professionalismLevel: "high",
    energyBaseline: "high",
    patienceLevel: "medium",
    commercialStyle: "closer",
    empathyLevel: "low",
    formalityLevel: "medium",
    salesPressure: "medium",
    energyStyle: "balanced",
    toneStyle: "direct",
  },
  kevin: {
    communicationStyle: "Commandes et dispo, exécution",
    warmthLevel: "medium",
    professionalismLevel: "medium",
    energyBaseline: "high",
    patienceLevel: "low",
    commercialStyle: "closer",
    empathyLevel: "low",
    formalityLevel: "medium",
    salesPressure: "medium",
    energyStyle: "dynamic",
    toneStyle: "direct",
  },
  jordan: {
    communicationStyle: "Commerce mobile, fluide",
    warmthLevel: "high",
    professionalismLevel: "medium",
    energyBaseline: "high",
    patienceLevel: "medium",
    commercialStyle: "conseiller",
    empathyLevel: "medium",
    formalityLevel: "low",
    salesPressure: "low",
    energyStyle: "dynamic",
    toneStyle: "conversational",
  },
  axel: {
    communicationStyle: "Support commande précis",
    warmthLevel: "medium",
    professionalismLevel: "high",
    energyBaseline: "medium",
    patienceLevel: "high",
    commercialStyle: "conseiller",
    empathyLevel: "medium",
    formalityLevel: "medium",
    salesPressure: "low",
    energyStyle: "balanced",
    toneStyle: "professional",
  },
};

const DEFAULT_TRAITS: Omit<AgentStablePersonality, "agentId" | "displayName"> = {
  communicationStyle: "Conseiller commercial WhatsApp",
  warmthLevel: "medium",
  professionalismLevel: "high",
  energyBaseline: "medium",
  patienceLevel: "medium",
  commercialStyle: "conseiller",
  empathyLevel: "medium",
  formalityLevel: "medium",
  salesPressure: "low",
  energyStyle: "balanced",
  toneStyle: "professional",
};

/** Charge la personnalité stable catalogue pour un agent. */
export function resolveAgentStablePersonality(personaKey: string | null | undefined): AgentStablePersonality {
  const id = resolveCommercialAgentKey(personaKey) ?? "grace";
  const profile = getAgentPersonalityProfile(id);
  const traits = TRAITS[id] ?? DEFAULT_TRAITS;
  return {
    agentId: id,
    displayName: profile?.displayName ?? id,
    ...traits,
  };
}

export function levelTo01(level: PersonalityLevel): number {
  return level === "low" ? 0.28 : level === "high" ? 0.82 : 0.55;
}
