import "server-only";

/**
 * Phrases type assistant / ChatGPT à filtrer ou éviter en sortie.
 * Source unique pour prompts (hard bans) et post-traitement.
 */
export const ANTI_AI_PHRASE_BLACKLIST: readonly string[] = [
  "Comment puis-je vous aider",
  "Je suis ravi",
  "Je suis ravie",
  "Ravi de",
  "Ravie de",
  "Enchanté",
  "Enchantée",
  "Je suis là pour vous aider",
  "Je peux vous aider",
  "Je peux vous assister",
  "N'hésitez pas",
  "N’hésitez pas",
  "Pas de souci",
  "Je comprends",
  "Je suis désolé",
  "Je suis désolée",
  "Avez-vous besoin d'autre chose",
  "Avez-vous besoin d’autre chose",
  "Je reste disponible",
  "Je reste à votre disposition",
  "Je vais faire de mon mieux",
  "Tu cherches des infos",
  "Tu cherches des informations",
  "Assistant IA",
  "assistant virtuel",
  "intelligence artificielle",
  "ChatGPT",
  "chatbot",
  "En tant qu'",
  "En tant qu’",
  "Voici une liste",
  "Voici les points",
  "How may I assist you",
  "How can I help you",
  "I'm here to help",
  "I am here to help",
  "Feel free to",
  "No worries",
  "Que recherchez-vous",
  "What are you looking for",
  "I'd be happy to",
  "I would be happy to",
  "Je serais heureux",
  "Je serais heureuse",
  "Je serais ravi",
  "Je serais ravie",
  "N'hésite pas",
  "N’hésite pas",
  "Puis-je vous aider",
  "Comment puis-je t'aider",
];
